### ISSUE TITLE
Authentication issues when running most roles

### ISSUE THREAD

**Issue by weiyentan** [redhat-cop/tower_configuration#52]
Hi,

I have been putting together my playbooks. and data structure. I have created my tower_auth.yml file with the necessary vars and encrypted it.

When I run the role for tower_settings  everything works so I was quite happy about that. However what I am finding is that the other roles keep coming up with errors such as this:

 msg: 'Failed to get token: HTTP Error 401: Unauthorized'
  response: '{"detail":"Authentication credentials were not provided. To establish a login session, visit /api/login/."}'

I can understand some of the roles are not working because of a templating error (I was using lookup plugin for the first time and I suspect i wasnt using it properly), but I would have thought that the other roles  would accept my login. any help would be appreciated.

**Comment by weiyentan** [comment]
So i have tried it with tower_oauthtoken and it looks like it is working fine with this. I am ok with this approach 

Not quite sure if it is still something that needs to be addressed but i am fine to close . I thought  it might be useful to bring up. Thank you

**Comment by kedark3** [comment]
@weiyentan thanks for opening the issue. `tower_oauthtoken` would be right way to authenticate as it can be reused by all roles/modules for auth during execution. 

Here's an example of it: 
```
- name: Create a new token using tower username/password
      awx.awx.tower_token:
        description: 'Creating token to test tower jobs'
        scope: "write"
        state: present
        tower_host: "{{ tower_hostname }}"
        tower_username: "{{ tower_username }}"
        tower_password: "{{ tower_password }}"
        validate_certs: False

    - name: Execute WF jobs
      awx.awx.tower_workflow_launch:
        name:  "{{ workflow_job.name }}"
        organization: Satellite
        extra_vars: "{{ workflow_job.extra_vars }}"
        tower_host: "{{ tower_hostname }}"
        tower_oauthtoken: "{{ tower_token }}"
        validate_certs: False
        wait: False  # Fire and forget
      loop: "{{ wf_jobs }}"
      loop_control:
        loop_var: workflow_job

```

In this example `awx.awx.tower_token:` is being used and it sets `tower_token` variable with appropriate token and that variable is accessible in the following tasks(or roles if you were to call roles). You can use `pre_tasks` where you use this authentication method and then all roles will use the token.

Please re-open the issue if you see more problems.
